# Generated by Django 3.1.2 on 2020-11-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('time', models.DateField(max_length=200)),
                ('imageUrl', models.CharField(max_length=200)),
                ('Url', models.URLField()),
            ],
        ),
    ]
