# Generated by Django 3.1 on 2020-11-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0003_courses_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='imageUrl',
            new_name='image',
        ),
    ]
