# Generated by Django 3.1 on 2020-11-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0004_auto_20201108_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
