# Generated by Django 3.1.2 on 2020-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0006_auto_20201108_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
