# Generated by Django 3.1.4 on 2020-12-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0008_auto_20201228_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
