# Generated by Django 3.1.4 on 2021-01-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0009_auto_20201228_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses'},
        ),
    ]
