# Generated by Django 3.1.4 on 2021-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0010_auto_20210125_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
