# Generated by Django 3.1.4 on 2021-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0011_auto_20210405_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='option',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
